# Generated by Django 4.2.4 on 2023-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
    ]
