# Generated by Django 4.2.4 on 2023-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_user_alter_book_author_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='قیمت'),
        ),
    ]
