# Generated by Django 4.2.4 on 2023-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
